<section>
    <div class="container">
        <div class="row">
            <?php include 'menu.phtml';?>
            <div class="col-sm-9 padding-right">
                <?php
                echo '<div class="features_items"><!--features_items-->
                          <h2 class="title text-center">Catalogo Tecnico - '.$this->Categoria.'</h2>';
                //stampo i singoli prodotti
                foreach($this->Prodotti as $prod){
                    $urlfoto = ($prod->Foto=='' || is_null($prod->Foto))?($this->baseURL().'/images/product-details/image-coming-soon.png'):($this->baseURL().'/images/products/'. $prod->Foto);
                    echo'<div class="col-sm-4">
							    <div class="product-image-wrapper">
								    <div class="single-products">
										<div class="productinfo text-center">
											<img src="'.$urlfoto.'" alt="" />
											<h2>'.$prod->Nome.'</h2>
											<p>'.$prod->DescrizioneBreve .'</p>
											<p></p>
											<a href='.$this->url(array(
                            'controller' => 'tecnico',
                            'action'     => 'schedaprodotto',
                            'prodotto' => $prod->id
                        ),
                            'default',true
                        ).' class="btn btn-default add-to-cart"><i class="fa fa-info">Vai alla scheda</i></a>
										</div>
								    </div>
							    </div>
						    </div>';
                }
                echo'</div><!--features_items-->';
                if($this->Prodotti instanceof Zend_Paginator) {
                    echo '<div class="text-center">'.$this->paginationControl($this->Prodotti,'Elastic','tecnico/_paginatorCatalogo.phtml').'</div>';
                }
                ?>
            </div>
        </div>
    </div>
</section>