<section>
    <div class="container">
        <div class="row">
            <?php include 'menu.phtml';?>
            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Risultati della ricerca</h2>
                    <div  id="cart_items" >
                        <div  class="table-responsive cart_info">
                            <table  class="table table-condensed">
                                <thead>
                                <tr class="cart_menu">
                                    <td class="description">Nome</td>
                                    <td class="description">Malfunzionamento</td>
                                    <td></td>
                                    <td class="description">Soluzione</td>
                                    <td></td>
                                </tr>
                                </thead>
                                <tbody id="fbody">'
                                <?php
                                if(sizeof($this->Malfunzionamenti)==0) echo'<td class="text-center"> Nessun malfunzionamento trovato.</td>';
                                foreach($this->Malfunzionamenti as $malf){
                                    $malfunzionamento =  strlen($malf->Malfunzionamento) > 50 ? substr($malf->Malfunzionamento,0,50)."..." : $malf->Malfunzionamento;
                                    $soluzione =  strlen($malf->Soluzione) > 50 ? substr($malf->Soluzione,0,50)."..." : $malf->Soluzione;
                                    echo'
                                <tr>
                                    <td class="cart_description">
                                        <p>'.$malf->Nome.'</p>
                                    </td>
                                    <td  class="cart_description">
                                        <p>'.$malfunzionamento.'</p>
                                        <div class="boxMalf" id="m-'.$malf->id.'">
                                            <p>'.$malf->Malfunzionamento.'</p>
                                        </div>
                                    </td>
                                    <td>
                                        <i class="fa fa-plus-square pointer" onclick="showMalf(this.id)" id="m-'.$malf->id.'"></i>
                                    </td>
                                    <td  class="cart_description">
                                        <p>'.$soluzione.'</p>
                                        <div class="boxSolution" id="s-'.$malf->id.'">
                                            <p>'.$malf->Soluzione.'</p>
                                        </div>
                                    </td>
                                    <td>
                                        <i class="fa fa-plus-square pointer" onclick="showSolution(this.id)" id="s-'.$malf->id.'"></i>
                                    </td>
                                </tr>';
                                }
                                echo'</tbody>
                            </table>
                        </div>
                    </div>';
                                if($this->Malfunzionamenti instanceof Zend_Paginator) {
                                    echo '<div class="text-center">'.$this->paginationControl($this->Malfunzionamenti,'Elastic','tecnico/_paginatorMalf.phtml').'</div>';
                                };?>
                        </div><!--features_items-->
                    </div>'
                </div>
            </div>
</section>