<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Categorie</h2>
                    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordian" href="#auto">
                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                        Auto
                                    </a>
                                </h4>
                            </div>
                            <div id="auto" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <?php echo $this->navigation()->menu()
                                        ->renderMenu($this->menuAuto)?>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordian" href="#moto">
                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                        Moto
                                    </a>
                                </h4>
                            </div>
                            <div id="moto" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <?php echo $this->navigation()->menu()
                                        ->renderMenu($this->menuMoto)?>
                                </div>
                            </div>
                        </div>
                    </div><!--/category-products-->

                </div>
            </div>

            <div class="col-sm-9 padding-right">

                <?php
                    echo '<h2 class="title text-center">Benvenuto nel centro assistenza BMW</h2><h2 class="text-center"><img class="border-radius" src="'. $this->baseURL().'/images/home/bmw-service-partner.jpg"></h2><br>';
                ?>
            </div>
        </div>
    </div>
</section>