<section>
    <div class="container">
        <div class="row">
            <?php include 'menu.phtml';?>
            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Lista dei Malfunzionamenti</h2>
                    <div  id="cart_items" >
                        <div  class="table-responsive cart_info">
                            <table  class="table table-condensed">
                                <thead>
                                <tr class="cart_menu">
                                    <td class="description">Malfunzionamento</td>
                                    <td class="description">Soluzione</td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                </thead>
                                <tbody id="fbody">
                                <?php
foreach($this->Malfunzionamenti as $malf){
    echo'<tr>
                                    <td  class="cart_description">';
    echo strlen($malf->Malfunzionamento) > 50 ?
        '<p id ="malfBreve-'.$malf->id.'" onclick="showDivRicerca(this.id)">'.substr($malf->Malfunzionamento,0,50).'...<i class="fa fa-plus"></i></p>
        <p style="display:none" id ="malfLungo-'.$malf->id.'" onclick="showDivRicerca(this.id)">'.$malf->Malfunzionamento.'<i class="fa fa-minus"></i></p>':
        '<p>'.$malf->Malfunzionamento.'</p>';
    echo'</td>
                <td  class="cart_description">';
    echo strlen($malf->Soluzione) > 50 ?
        '<p id ="solBreve-'.$malf->id.'" onclick="showDivRicerca(this.id)">'.substr($malf->Soluzione,0,50).'...<i class="fa fa-plus"></i></p>
        <p style="display:none" id ="solLungo-'.$malf->id.'" onclick="showDivRicerca(this.id)">'.$malf->Soluzione.'<i class="fa fa-minus"></i></p>':
        '<p>'.$malf->Soluzione.'</p>';
    echo '</td>
                                </tr>';
}
echo'</tbody>
                            </table>
                        </div>
                    </div>';
if($this->Malfunzionamenti instanceof Zend_Paginator) {
    echo '<div class="text-center">'.$this->paginationControl($this->Malfunzionamenti,'Elastic','tecnico/_paginatorMalf.phtml').'</div>';
};?>
                        </div><!--features_items-->
            </div>'
                </div>
            </div>
</section>