<section>
    <div class="container">
        <div class="row">
            <?php include 'menu.phtml';?>
            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Modifica Malfunzionamenti</h2>
                    <div  id="cart_items" >
                        <div  class="table-responsive cart_info">
                            <table  class="table table-condensed">
                                <thead>
                                <tr class="cart_menu">
                                    <td class="description">Malfunzionamento</td>
                                    <td class="description">Soluzione</td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
foreach($this->Malfunzionamenti as $malf){
    $malfunzionamento =  strlen($malf->Malfunzionamento) > 50 ? substr($malf->Malfunzionamento,0,50)."..." : $malf->Malfunzionamento;
    $soluzione =  strlen($malf->Soluzione) > 50 ? substr($malf->Soluzione,0,50)."..." : $malf->Soluzione;
    echo'<tr>
                                    <td  class="cart_description">
                                        <p>'.$malfunzionamento.'</p>
                                    </td>
                                    <td  class="cart_description">
                                        <p> '.$soluzione.'</p>
                                    </td>
                                </tr>';
}
echo'</tbody>
                            </table>
                        </div>
                    </div>';
if($this->Malfunzionamenti instanceof Zend_Paginator) {
    echo '<div class="text-center">'.$this->paginationControl($this->Malfunzionamenti,'Elastic','tecnico/_paginatorMalf.phtml').'</div>';
};?>
                        </div><!--features_items-->
            </div>'
                </div>
            </div>
</section>