<div class="overlay" id="overlay" style="display:none;" onclick="chiudiOverlay()"></div>
<?php
foreach($this->Componenti as $comp){
	$urlfoto = ($comp->Foto=='' || is_null($comp->Foto))?($this->baseURL().'/images/product-details/image-coming-soon.png'):($this->baseURL() .'/images/component/'. $comp->Foto);
	echo'<div class="box" id="comp'.$comp->id.'">
		<div class="product-details" ><!--product-details-->
            <div class="col-sm-5">
                <div class="view-product">
                    <img src="'.$urlfoto.'" alt="" />
                </div>

            </div>
            <div class="col-sm-7">
                <div class="product-information"><!--/product-information-->

                    <h2>'.$comp->Nome.'</h2>
                    <p> ID: '.$comp->id.'</p>
                </div><!--/product-information-->
            </div>
        </div><!--/product-details-->

        <div class="category-tab shop-details-tab"><!--category-tab-->
            <div class="col-sm-12">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#descrizione" data-toggle="tab">Descrizione</a></li>
                </ul>
            </div>
            <div class="tab-content">
                <div class="tab-pane fade active in" id="descrizione" >
                    <div class="col-sm-12">
                        <p>'.$comp->Descrizione.'</p>
                    </div>
                </div>
            </div>
            <p class="chiudi" onclick="chiudiOverlay()">CHIUDI<i class="fa fa-times"></i></p>
        </div><!--/category-tab-->
        </div>';
}

foreach($this->Malfunzionamenti as $malf)
{
echo'<div class="box" id="malf'.$malf->id.'">
	<h1 class="titolo_box">'.$malf->Nome.'</h1>
	<div class="step-one title text-center">
        <h2 class="heading">Malfunzionamento</h2>
    </div>
	<div><p>'.$malf->Malfunzionamento.'</p></div>
	<div class="step-one title text-center">
        <h2 class="heading">Soluzione</h2>
    </div>
	<div ><p>'.$malf->Soluzione.'</p></div>
	<p class="chiudi" onclick="chiudiOverlay()">CHIUDI<i class="fa fa-times"></i></p>
</div>  <!--fine box-->';
};
?>
<section>
    <div class="container">
        <div class="row">
            <?php include 'menu.phtml';?>
            <div class="col-sm-9 padding-right">
                <?php
                $urlfoto = ($this->Prodotto->Foto=='' || is_null($this->Prodotto->Foto))?($this->baseURL().'/images/product-details/image-coming-soon.png'):($this->baseURL() .'/images/products/'. $this->Prodotto->Foto);
                echo'<div class="features_items"><!--features_items-->
                     <h2 class="title text-center">Catalogo Tecnico</h2>
                        <div class="col-sm-9 padding-right">
					        <div class="product-details"><!--product-details-->
						        <div class="col-sm-5">
							        <div class="view-product">
								    <img src="'.$urlfoto.'" alt="" />
							    </div>
						    </div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
							<h2>'.$this->Prodotto->Nome.'</h2>
							<p>Web ID:'.$this->Prodotto->id.'</p>
							<p><b>Cilindrata:</b> '.$this->Prodotto->Cilindrata.' cm&sup3;</p>
							<p><b>Potenza:</b> '.$this->Prodotto->Potenza.' CV</p>
							<p><b>Velocità massima:</b> '.$this->Prodotto->VelocitaMax.' km/h</p>
							<p><b>Massa a vuoto:</b> '.$this->Prodotto->MassaVuoto.' Kg</p>
							</div><!--/product-information-->
						</div>
					</div><!--/product-details-->
					<div class="category-tab shop-details-tab"><!--category-tab-->
						<div class="col-sm-12">
							<ul class="nav nav-tabs">
							    <li class="active"><a href="#descrizione" data-toggle="tab">Descrizione</a></li>
								<li><a href="#ntbu" data-toggle="tab">Note tecniche buon uso</a></li>
								<li><a href="#componenti" data-toggle="tab">Componenti</a></li>
								<li><a href="#malfunzionamenti" data-toggle="tab">Malfunzionamenti</a></li>
							</ul>
						</div>
						<div class="tab-content">
						    <div class="tab-pane fade active in" id="descrizione" >
								<div class="col-sm-12">
								    <p>'.$this->Prodotto->DescrizioneLunga.'</p>
								</div>
							</div>
							<div class="tab-pane fade" id="ntbu" >
								<div class="col-sm-12">
								    <p>Lista note tecniche di buon uso:</p>
								    <ul class="componenti">';
                foreach($this->Ntbu as $ntbu)
                {
                    echo '<div class="faq-c">
                                <div class="faq-q"><span class="faq-t">+</span>'.$ntbu->Nome.'</div>
                                <div class="faq-a">
                                <p>'.$ntbu->Descrizione.'</p>
                                </div>
                             </div>';
                };echo'
                </ul>

								</div>
							</div>
							<div class="tab-pane fade" id="componenti" >
								<div class="col-sm-12">
								    <p > Lista componenti:</p>
								        <ul class="componenti">';
				foreach($this->Componenti as $comp)
				{	echo '<li><span id="'.$comp->id.'" onclick="mostraComponente(this.id)">-'.$comp->Nome.'</span></li>';
				}
                echo '</ul>
								</div>
							</div>
							<div class="tab-pane fade" id="malfunzionamenti" >
								<div class="col-sm-12">
								<div class="search_box pull-right">
									<input id="querymalflist" type="text" placeholder="Cerca nella lista"/>
								</div>
								<p> Lista Malfunzionamenti:</p>
								<ul id="ul-malf">';
								foreach($this->Malfunzionamenti as $malf)
								{	echo '<li id="'.$malf->id.'"><span id="'.$malf->id.'" onclick="mostraMalfunzionamento(this.id)">-'.$malf->Nome.'</span></li>';
								}?>
								</ul>
								</div>
							</div>
						</div>
					</div><!--/category-tab-->
				</div>
			</div><!--features_items-->
            </div>
        </div>
    </div>
</section>