<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Categorie</h2>
                    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordian" href="#auto">
                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                        Auto
                                    </a>
                                </h4>
                            </div>
                            <div id="auto" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <?php echo $this->navigation()->menu()
                                        ->renderMenu($this->menuAuto)?>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordian" href="#moto">
                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                        Moto
                                    </a>
                                </h4>
                            </div>
                            <div id="moto" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <?php echo $this->navigation()->menu()
                                        ->renderMenu($this->menuMoto)?>
                                </div>
                            </div>
                        </div>
                    </div><!--/category-products-->
                </div>
            </div>

            <div class="col-sm-9 padding-right">
                <?php
                $urlfoto = ($this->Componente->Foto=='' || is_null($this->Componente->Foto))?($this->baseURL().'/images/product-details/image-coming-soon.png'):($this->baseURL() .'/images/component/'. $this->Componente->Foto);
                echo'<div class="features_items"><!--features_items-->
    <h2 class="title text-center">Catalogo Tecnico</h2>
    <div class="col-sm-9 padding-right">
        <div class="product-details"><!--product-details-->
            <div class="col-sm-5">
                <div class="view-product">
                    <img src="'.$urlfoto.'" alt="" />
                </div>

            </div>
            <div class="col-sm-7">
                <div class="product-information"><!--/product-information-->

                    <h2>'.$this->Componente->Nome.'</h2>
                </div><!--/product-information-->
            </div>
        </div><!--/product-details-->

        <div class="category-tab shop-details-tab"><!--category-tab-->
            <div class="col-sm-12">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#descrizione" data-toggle="tab">Descrizione</a></li>
                </ul>
            </div>
            <div class="tab-content">
                <div class="tab-pane fade active in" id="descrizione" >
                    <div class="col-sm-12">
                        <p>'.$this->Componente->Descrizione.'</p>
                    </div>
                </div>
            </div>
        </div><!--/category-tab-->
    </div>
</div><!--features_items-->';
                ?>
            </div>
        </div>
    </div>
</section>



