<?php $this->headScript()
    ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
    ->captureStart() ?>

// codice jQuery inserito da view-script nella sezione head della pagina
$(function(){
    $('#selectProdotti').change(function(event){
        //inizio loading
var over = '<div id="overlay">' +
    '<img id="loading" src="<?php echo $this->baseURL();?>/images/ajax-loader.gif">' +
    '</div>';
$(over).appendTo('body');
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->url(array(
                            'controller' => 'staff',
                            'action' => 'populatemalf'
                        ),
                            'default'
                        )?>',
            data: { id: $('#selectProdotti').val() },
            dataType: 'json',
complete: function(){
$('#overlay').remove();
},
            success: function(data){
setMalfunzionamenti(data);
},
error:function(){
alert("fail :(");
}
        });
    });

    function setMalfunzionamenti(data){
$(':checkbox').prop('checked',false);
        for(var i in data){
$(':checkbox#'+data[i]).prop('checked', true)
    }
    }
});

<?php $this->headScript()->captureEnd() ?>


<section>
    <h3>Associa Malfunzionamento</h3>
    <p>Utilizza questa pagina per gestire l'associazione tra prodotti e malfunzionamenti.</p>
    <select class="col-sm-3" id="selectProdotti">
            <?php
            foreach($this->Prodotti as $prod)
                {
                    echo '<option value="'.$prod->id.'">'.$prod->Nome.'</option>';
                }
            ?>
    </select>
    <div class="col-sm-6" id="checkboxes">
        <?php
        foreach($this->Malfunzionamenti as $malf)
        {
            echo '<input type="checkbox"  id="'.$malf->id.'">'.$malf->Malfunzionamento.'</input>';
        }
        ?>
    </div>
</section>