<?php $this->headScript()
    ->captureStart() ?>

// codice jQuery inserito da view-script nella sezione head della pagina
$(function(){
    $('#selectProdotti').change(function(event){
        //inizio loading
        var over = '<div id="overlay">' +
            '<img id="loading" src="<?php echo $this->baseURL();?>/images/ajax-loader.gif">' +
            '</div>';
        $(over).appendTo('body');
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->url(array(
                            'controller' => 'staff',
                            'action' => 'populatemalf'
                        ),
                            'default'
                        )?>',
            data: { id: $('#selectProdotti').val() },
            dataType: 'json',
            complete: function(){
                $('#overlay').remove();
            },
            success: function(data){
                setMalfunzionamenti(data);
                },
                error:function(){
                alert("fail :(");
            }
        });
    });
    function setMalfunzionamenti(data){
        $('div#steptwo').show();
        $(':checkbox').prop('checked',false);
        for(var i in data){
            $(':checkbox#'+data[i]).prop('checked', true)
        }
    }
});

<?php $this->headScript()->captureEnd() ?>


<div class="col-sm-9 padding-right">
    <h3>Associa Malfunzionamento</h3>
    <p>Utilizza questa pagina per gestire l'associazione tra prodotti e malfunzionamenti.</p>
    <div class="step-one title text-center col-md-6">
        <h2 class="heading">Step 1</h2>
    </div>
    <div class="col-md-9">
        <p>Scegli un prodotto:</p>
        <?php $action =$this->url(array(
            'controller' => 'staff',
            'action' => 'associamalfunzionamento'
        ),
            'default'
        ) ?>
        <form class="step-two" id="associatemalfunction" action="<?= $action ?>" method="post" enctype="application/x-www-form-urlencoded" name="associatemalfunction">
        <select class="col-sm-4" id="selectProdotti" name="selectProdotti" >
            <option value="" disabled selected>Seleziona un prodotto</option>
            <?php
            foreach($this->Prodotti as $prod)
            {
                echo '<option value="'.$prod->id.'">'.$prod->Nome.'</option>';
            }
            ?>
        </select>
    </div>
    <div id ="steptwo" style="display: none">
    <div class="step-one title text-center col-md-6">
        <h2 class="heading">Step2</h2>
    </div>
    <div class="col-sm-9" id="checkboxes">
        <p>Scegli i malfunzionamenti da associare:</p>
        <table>
            <?php
            foreach($this->Malfunzionamenti as $malf)
            {
                echo '<tr>
                <td>
                <input type="checkbox" name="malf[]" value="'.$malf->id.'" id="'.$malf->id.'">'.$malf->Nome.'</input>
                </td>
                </tr>
                ';
            }
            ?>
        </table>
    </div>
        <div class="col-md-9">
        <input type="submit" value="Associa malfunzionamenti">
        </form>
            </div>
    </div>
</div>