<?php
echo'<div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Modifica Malfunzionamenti</h2>
                    <div class="search_box pull-right">
                        <input id="querymalf" type="text" placeholder="Cerca nella lista"/>
                    </div>
                    <div  id="cart_items" >
                        <div  class="table-responsive cart_info">
                            <table  class="table table-condensed">
                                <thead>
                                <tr class="cart_menu">
                                    <td class="description">Malfunzionamento</td>
                                    <td class="description">Soluzione</td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                </thead>
                                <tbody id="fbody">';
foreach($this->Malfunzionamenti as $malf){
    $malfunzionamento =  strlen($malf->Malfunzionamento) > 50 ? substr($malf->Malfunzionamento,0,50)."..." : $malf->Malfunzionamento;
    $soluzione =  strlen($malf->Soluzione) > 50 ? substr($malf->Soluzione,0,50)."..." : $malf->Soluzione;
    echo'<tr>
                                    <td  class="cart_description">
                                        <p>'.$malfunzionamento.'</p>
                                    </td>
                                    <td  class="cart_description">
                                        <p> '.$soluzione.'</p>
                                    </td>
                                    <td  class="cart_delete">
                                        <p><a class="cart_quantity_delete" href="'.$this->url(array(
            'controller' => 'staff',
            'action'     => 'updatemalfunction',
            'id' => $malf->id
        ),
            'default',true
        ).'"><i class="fa fa-pencil">Modifica</i></a></p>
                                        <p><a class="cart_quantity_delete" href="'.$this->url(array(
            'controller' => 'staff',
            'action'     => 'cancellamalfunzionamento',
            'id' => $malf->id
        ),
            'default',true
        ).'"><i class="fa fa-times">Cancella</i></a></p>
                                    </td>
                                </tr>';
}
echo'</tbody>
                            </table>
                        </div>
                    </div>';
if($this->Malfunzionamenti instanceof Zend_Paginator) {
    echo '<div class="text-center">'.$this->paginationControl($this->Malfunzionamenti,'Elastic','staff/_paginatorMalf.phtml').'</div>';
};
echo '</div><!--features_items-->
            </div>';