<?php $this->headTitle()->append('Contatti');?>
<section>
    <div class="container">

<div class="row">
    <div class="col-sm-8">
        <div class="contact-form">
            <h2 class="title text-center">Contattaci</h2>
            <div class="status alert alert-success" style="display: none"></div>
            <?php echo $this->emailForm; ?>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="contact-info">
            <h2 class="title text-center">Contact Info</h2>
            <address>
                <p>Gruppo 55, Tecnologie web</p>
                <p>Via Brecce Bianche, Ancona (AN), Italia</p>
                <p><i class="fa fa-phone"></i><a href="skype:+391234567890?call">Telefono: +39 123 456 7890</a></p>
                <p><i class="fa fa-mobile"></i><a href="skype:+391234567890?call">Mobile: +39 123 456 7890</a></p>
                <p><i class="fa fa-fax"></i><a href="skype:+391234567890?call">Fax: +39 123 456 7890</a></p>
                <p><i class="fa fa-skype"></i><a href="skype:grp55tw?call">Skype: grp55tw</a></p>
                <p><i class="fa fa-envelope"></i> Email: <a href="mailto:grp55tw@gmail.com">grp55tw@gmail.com</a></p>
            </address>
            <div class="social-networks">
                <h2 class="title text-center">Social Networking</h2>
                <ul>
                    <li>
                        <a href="http://www.facebook.com"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li>
                        <a href="http://www.twitter.com"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li>
                        <a href="http://plus.google.com"><i class="fa fa-google-plus"></i></a>
                    </li>
                    <li>
                        <a href="http://www.youtube.com"><i class="fa fa-youtube"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
    </div>
</section>

