<div class="row">
    <div class="col-sm-3">
        <div class="left-sidebar">
            <h2>Category</h2>
            <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordian" href="#sportswear">
                                <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                Auto
                            </a>
                        </h4>
                    </div>
                    <div id="sportswear" class="panel-collapse in">
                        <div class="panel-body">
                            <ul>
                                <?php

                                foreach($this->CategorieA as $cat){
                                    echo '<li><a href='.$this->url(array(
                                            'controller' => 'public',
                                            'action'     => 'index',
                                            'categoria' => $cat->Nome
                                        ),
                                            'default',true
                                        ).'>' . $cat->Nome . '</a></li>';
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordian" href="#mens">
                                <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                Moto
                            </a>
                        </h4>
                    </div>
                    <div id="mens" class="panel-collapse collapse">
                        <div class="panel-body">
                            <ul>
                                <?php
                                foreach($this->CategorieM as $cat){
                                    echo '<li><a href='.$this->url(array(
                                            'controller' => 'public',
                                            'action'     => 'index',
                                            'categoria' => $cat->Nome
                                        ),
                                            'default',true
                                        ).'>' . $cat->Nome . '</a></li>';
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div><!--/category-products-->

        </div>
    </div>

    <div class="col-sm-9 padding-right">
        <div class="features_items"><!--features_items-->
            <h2 class="title text-center">COPYRIGHT - ALL RIGHTS RESERVED</h2>
            <p>I CONTENUTI DEL SITO WEB POSSONO ESSERE LIBERAMENTE COPIATI DA ALTRI SITI INTERNET A SCOPO DI CRITICA, CONFRONTO E RICERCA, CITANDO GLI AUTORI E LINKANDO LA FONTE</p>

            <p>&copy; Copyright</p>

            <p>All rights reserved</p>

            <p>Tutti i diritti sono riservati. &Egrave; vietata qualsiasi utilizzazione, totale o parziale, dei contenuti inseriti nel presente portale, ivi inclusa la memorizzazione, riproduzione, rielaborazione, diffusione o distribuzione dei contenuti stessi mediante qualunque piattaforma tecnologica, supporto o rete telematica, senza previa autorizzazione scritta da parte degli amministratori.</p>
        </div><!--features_items-->
    </div>