<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Frequently Asked Questions</h2>
                    <?php
                    echo '<dl id="faqs">';
                    foreach ($this->Faq as $faq)
                    {
                        echo'<div class="faq-c">
                                <div class="faq-q"><span class="faq-t">+</span>'.$faq->Domanda.'</div>
                                <div class="faq-a">
                                <p>'.$faq->Risposta.'</p>
                                </div>
                             </div>';

                        echo'<script>
                               $(".faq-q").click( function () {
  var container = $(this).parents(".faq-c");
  var answer = container.find(".faq-a");
  var trigger = container.find(".faq-t");

  answer.slideToggle(200);

  if (trigger.hasClass("faq-o")) {
    trigger.removeClass("faq-o");
  }
  else {
    trigger.addClass("faq-o");
  }
});</script>';
                    }
                    ?>
                </div><!--features_items-->
            </div>
        </div>
    </div>
</section>