<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Categorie</h2>
                    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordian" href="#auto">
                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                        Auto
                                    </a>
                                </h4>
                            </div>
                            <div id="auto" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <?php echo $this->navigation()->menu()
                                        ->renderMenu($this->menuAuto)?>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordian" href="#moto">
                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                        Moto
                                    </a>
                                </h4>
                            </div>
                            <div id="moto" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <?php echo $this->navigation()->menu()
                                        ->renderMenu($this->menuMoto)?>
                                </div>
                            </div>
                        </div>
                    </div><!--/category-products-->
                </div>
            </div>
            <div class="col-sm-9 padding-right">
                <div id="slider-carousel" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#slider-carousel" data-slide-to="1"></li>
                        <li data-target="#slider-carousel" data-slide-to="2"></li>
                    </ol>

                    <div class="carousel-inner">
                        <div class="item active">
                            <div class="col-sm-3">
                                <h1><span>BMW </span>ASSISTANCE</h1>
                                <h2>Benvenuto nel centro assistenza BMW</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                            </div>
                            <div class="col-sm-6">
                                <img src="'<?= $this->baseURL()?>'/images/home/bmw-service-partner.jpg" class="border-radius girl img-responsive" alt="" />
                            </div>
                        </div>

                    </div>
                    <div class="carousel-inner">
                        <div class="item">
                            <div class="col-sm-3">
                                <h1><span>BMW </span>ASSISTANCE</h1>
                                <h2>Benvenuto nel centro assistenza BMW</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                            </div>
                            <div class="col-sm-6">
                                <img src="'<?= $this->baseURL()?>'/images/home/bmw-service-partner.jpg" class="border-radius girl img-responsive" alt="" />
                            </div>
                        </div>

                    </div>
                    <div class="carousel-inner">
                        <div class="item">
                            <div class="col-sm-3">
                                <h1><span>BMW </span>ASSISTANCE</h1>
                                <h2>Benvenuto nel centro assistenza BMW</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                            </div>
                            <div class="col-sm-6">
                                <img src="'<?= $this->baseURL()?>'/images/home/bmw-service-partner.jpg" class="border-radius girl img-responsive" alt="" />
                            </div>
                        </div>

                    </div>

                    <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>

                <h2 class="title text-center">Benvenuto nel centro assistenza BMW</h2><h2 class="text-center"><img class="border-radius" src="'<?= $this->baseURL()?>'/images/home/bmw-service-partner.jpg"></h2><br>';

            </div>
        </div>
    </div>
</section>