<div class="row">
    <div class="col-sm-3">
        <div class="left-sidebar">
            <h2>Category</h2>
            <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordian" href="#sportswear">
                                <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                Auto
                            </a>
                        </h4>
                    </div>
                    <div id="sportswear" class="panel-collapse collapse">
                        <div class="panel-body">
                            <ul>
                            <?php

                            foreach($this->CategorieA as $cat){
                                echo '<li><a href='.$this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'index',
                                        'categoria' => $cat->Nome
                                    ),
                                        'default',true
                                    ).'>' . $cat->Nome . '</a></li>';
                            }
                            ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordian" href="#mens">
                                <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                Moto
                            </a>
                        </h4>
                    </div>
                    <div id="mens" class="panel-collapse collapse">
                        <div class="panel-body">
                            <ul>
                                <?php
                                foreach($this->CategorieM as $cat){
                                    echo '<li><a href='.$this->url(array(
                                            'controller' => 'public',
                                            'action'     => 'index',
                                            'categoria' => $cat->Nome
                                        ),
                                            'default',true
                                        ).'>' . $cat->Nome . '</a></li>';
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div><!--/category-products-->

        </div>
    </div>

    <div class="col-sm-9 padding-right">
        <div class="features_items"><!--features_items-->
            <?php
            if(is_null($this->Categoria)){
                echo '<h2 class="title text-center">Home-Page</h2>';
            }else{
                echo '<h2 class="title text-center">Catalogo - '.$this->Categoria.'</h2>';
                foreach($this->Prodotti as $prod){
                    echo'<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<img src="'. $this->baseURL().'/images/home/product1.jpg" alt="" />
											<h2>'.$prod->Nome.'</h2>
											<p>'.$prod->DescrizioneBreve .'</p>
											<p></p>
											<a href='.$this->url(array(
                            'controller' => 'public',
                            'action'     => 'index',
                            'prodotto' => $prod->id
                        ),
                            'default',true
                        ).' class="btn btn-default add-to-cart"><i class="fa fa-info">  Vai alla scheda</i></a>
										</div>
								</div>
							</div>
						</div>';
                }
            }
            ?>

        </div><!--features_items-->




    </div>




