<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-1">
                <div class="features_items">
                    <h2 class="title text-center">Invio E-mail</h2>
                    <div>
                        <h3>Invio della E-mail avvenuto con successo.</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>