<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-1">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Login</h2>
                    <div class="login-form"><!--login form-->
                        <h2>Login to your account</h2>
                        <?=$this->loginForm; ?>
                    </div><!--/login form-->
                    <p>* Parametro richiesto</p>
                </div><!--features_items-->
            </div>
        </div>
    </div>
</section>