<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Categorie</h2>
                    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordian" href="#auto">
                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                        Auto
                                    </a>
                                </h4>
                            </div>
                            <div id="auto" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <ul>
                                        <?php
                                        foreach($this->CategorieA as $cat){
                                            echo '<li><a href='.$this->url(array(
                                                    'controller' => 'public',
                                                    'action'     => 'index',
                                                    'categoria' => $cat->Nome
                                                ),
                                                    'default',true
                                                ).'>' . $cat->Nome . '</a></li>';
                                        }
                                        ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordian" href="#moto">
                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                        Moto
                                    </a>
                                </h4>
                            </div>
                            <div id="moto" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <ul>
                                        <?php
                                        foreach($this->CategorieM as $cat){
                                            echo '<li><a href='.$this->url(array(
                                                    'controller' => 'public',
                                                    'action'     => 'index',
                                                    'categoria' => $cat->Nome
                                                ),
                                                    'default',true
                                                ).'>' . $cat->Nome . '</a></li>';
                                        }
                                        ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div><!--/category-products-->

                </div>
            </div>

            <div class="col-sm-4 col-sm-offset-1">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Login</h2>
                    <div class="login-form"><!--login form-->
                        <h2>Login to your account</h2>
                        <form action="#">
                            <input type="text" placeholder="Name" />
                            <input type="email" placeholder="Email Address" />
							<span>
								<input type="checkbox" class="checkbox">
								Keep me signed in
							</span>
                            <button type="submit" class="btn btn-default">Login</button>
                        </form>
                        <?=$this->loginForm; ?>
                    </div><!--/login form-->
                </div><!--features_items-->
            </div>
        </div>
    </div>
</section>