<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Categorie</h2>
                    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                        <?php foreach($this->TopCats as $topcat)
                        { echo '<div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordian" href="#'.$topcat['Nome'].'">
                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                        '.$topcat['Nome'].'
                                    </a>
                                </h4>
                            </div>
                            <div id="'.$topcat['Nome'].'" class="panel-collapse collapse">
                                <div class="panel-body">';
                            echo $this->navigation()->menu()
                                ->renderMenu($this->Menu[$topcat['Nome']]);
                            echo '
                                </div>
                            </div>
                        </div>';
                        } ?>

                    </div><!--/category-products-->
                </div>
            </div>

            <div class="col-sm-9 padding-right">
                <?php
                $urlfoto = ($this->Prodotto->Foto=='' || is_null($this->Prodotto->Foto))?($this->baseURL().'/images/product-details/image-coming-soon.png'):($this->baseURL() .'/images/products/'. $this->Prodotto->Foto);
                echo'<div class="features_items"><!--features_items-->
                     <h2 class="title text-center">Catalogo Pubblico</h2>
                        <div class="col-sm-12 padding-right">
					        <div class="product-details"><!--product-details-->
						        <div class="col-sm-5">
							        <div class="view-product">
								    <img src="'.$urlfoto.'" width="20%"alt="" />
							    </div>
						    </div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
							<h2>'.$this->Prodotto->Nome.'</h2>
							<p>Web ID:'.$this->Prodotto->id.'</p>
							<p><b>Cilindrata:</b> '.$this->Prodotto->Cilindrata.' cm&sup3;</p>
							<p><b>Potenza:</b> '.$this->Prodotto->Potenza.' CV</p>
							<p><b>Velocità massima:</b> '.$this->Prodotto->VelocitaMax.' km/h</p>
							<p><b>Massa a vuoto:</b> '.$this->Prodotto->MassaVuoto.' Kg</p>
							</div><!--/product-information-->
						</div>
					</div><!--/product-details-->
					<div class="category-tab shop-details-tab"><!--category-tab-->
						<div class="col-sm-12">
							<ul class="nav nav-tabs">
							    <li class="active"><a href="#descrizione" data-toggle="tab">Descrizione</a></li>
								<li><a href="#ntbu" data-toggle="tab">Note tecniche buon uso</a></li>
							</ul>
						</div>
						<div class="tab-content">
						    <div class="tab-pane fade active in" id="descrizione" >
								<div class="col-sm-12">
								    <p>'.$this->Prodotto->DescrizioneLunga.'</p>
								</div>
							</div>
							<div class="tab-pane fade" id="ntbu" >
								<div class="col-sm-12">
								    <p>Lista note tecniche di buon uso:</p>
								    <ul class="componenti">';
				foreach($this->Ntbu as $ntbu)
				{
					echo '<div class="faq-c">
                                <div class="faq-q"><span class="faq-t">+</span>'.$ntbu->Nome.'</div>
                                <div class="faq-a">
                                <p>'.$ntbu->Descrizione.'</p>
                                </div>
                             </div>';
				};
				echo'
                </ul>

								</div>
							</div>
						</div>
					</div><!--/category-tab-->
				</div>
			</div><!--features_items-->';
                ?>
            </div>
        </div>
    </div>
</section>