<?php $this->headTitle()->append('Dove siamo');?>
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="left-sidebar">
                    <h2>LISTA CENTRI ASSISTENZA</h2>
                    Click su un centro per mostrare i dettagli
                    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                        <?php foreach($this->Centri as $centro)
                        { echo '<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a onclick="mostraCentro('.$centro['id'].')" >'.$centro['Nome'].'</a></h4>
								</div>
							</div>';
                        } ?>

                    </div><!--/category-products-->
                </div>
            </div>
            <div class="col-sm-8 padding-right">
                <h2 class="title text-center">DOVE SIAMO</h2>
                <style>
                    #map {
                        width: 400px;
                        height: 400px;
                    }
                </style>
                <script src="https://maps.googleapis.com/maps/api/js"></script>
                <script>
                    var map, marker, infowindow;
                    var locations = new Array();

                    <?php
                     $i=0; foreach($this->Centri as $centro)
                    {
                    echo"locations[".$i."]=[".$centro['id'].",'".$centro['Nome']."','".$centro['Indirizzo']."',".$centro['Latitudine'].",".$centro['Longitudine']."];\n";
                    $i++;
                    };
                    ?>

                    function infoCentro(id){
                        var arrayLenght = locations.length;
                        for(var i = 0; i<arrayLenght;i++){
                            if(locations[i][0]==id){
                                return locations[i];
                            }
                        }
                    }

                    function mostraCentro(id){
                        //mostro il div del centro
                        $('.contact').hide("slow");
                        $('#'+id).show("slow");

                        //recupero le info sul centro
                        var centro = infoCentro(id);

                        //cambio la posizione al marker e al centro della mappa
                        var latlng = new google.maps.LatLng(centro[3],centro[4]);
                        marker.setPosition(latlng);
                        map.setCenter(latlng);
                        var string = '<b>' + centro[1] +'</b></br>' + centro[2];
                        infowindow.setContent(string);
                        infowindow.open(map, marker);

                    }

                    function initialize() {
                        var mapCanvas = document.getElementById('map');

                        infowindow = new google.maps.InfoWindow();

                        var mapOptions = {
                            center: new google.maps.LatLng(locations[0][3],locations[0][4]),
                            zoom: 10,
                            mapTypeId: google.maps.MapTypeId.ROADMAP
                        }
                        map = new google.maps.Map(mapCanvas, mapOptions)

                        marker = new google.maps.Marker({
                            position: new google.maps.LatLng(locations[0][3], locations[0][4]),
                            map: map
                        });

                        var string = '<b>' + locations[0][1] +'</b></br>' + locations[0][2];
                        infowindow.setContent(string);
                        infowindow.open(map, marker);

                        //mostro il primo centro
                        //mostro il div del centr
                        $('#'+<?php echo $this->Centri[0]['id'];?>).show();
                    }
                    google.maps.event.addDomListener(window, 'load', initialize);
                </script>
                <div id="map" class="col-sm-6"></div>
                <?php foreach($this->Centri as $centro)
                    {
                       echo'<div class="col-sm-4 contact" id="'.$centro->id.'" style="display:none">
                                            <div class="contact-info">
                                                <h2 class="title text-center">Contact Info</h2>
                                                <address>
                                                    <p><b>'.$centro->Nome.'</b></p>
                                                    <p>'.$centro->Indirizzo.'</p>
                                                    <p><i class="fa fa-phone"></i>Telefono: <a href="skype:'.$centro->Telefono.'?call"> '.$centro->Telefono.'</a></p>';
                            $mobile = ((is_null($centro->Mobile) || $centro->Mobile==='') ? '': '<p><i class="fa fa-mobile"></i>Mobile:<a href="skype:'.$centro->Mobile.'?call"> '.$centro->Mobile.'</a></p>' );
                            $fax = ((is_null($centro->Fax) || $centro->Fax=='') ? '': '<p><i class="fa fa-fax"></i>Fax:<a href="skype:'.$centro->Fax.'?call"> '.$centro->Fax.'</a></p>' );
                            $skype = ((is_null($centro->Skype) || $centro->Skype=='') ? '': '<p><i class="fa fa-skype"></i>Skype: <a href="skype:'.$centro->Skype.'?call"> '.$centro->Skype.'</a></p>' );
                            $email = ((is_null($centro->Email) || $centro->Email=='') ? '': '<p><i class="fa fa-envelope"></i>Email: <a href="mailto:'.$centro->Email.'"> '.$centro->Email.'</a></p>' );
                            $sito = ((is_null($centro->Sito) || $centro->Sito=='') ? '': '<p><i class="fa fa-globe"></i>Sito: <a href="'.$centro->Sito.'"> '.$centro->Sito.'</a></p>' );
                            echo $mobile.
                                $fax.
                                $skype.
                                $email.
                                $sito.'
                                                   </address>
                                                <div class="contact-info">
                                                    <h2 class="title text-center">Lista tecnici</h2>
                                                    ';
                            foreach($this->Tecnici[$centro['id']] as $tec)
                            {
                                echo '<p><i class="fa fa-user"></i>'. $tec['Nome'].' <i class="fa fa-envelope"></i><a href="mailto:'.$tec->Email.'">'.$tec->Email.'</a></p>';
                            }
                            echo'</div>
                        </div>
                    </div>';
                }?>
            </div>
        </div>
    </div>
</section>