<section>
    <div class="container">
<div class="row">
    <div class="col-sm-3">
        <div class="left-sidebar">
            <h2>Category</h2>
            <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordian" href="#sportswear">
                                <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                Auto
                            </a>
                        </h4>
                    </div>
                    <div id="sportswear" class="panel-collapse in">
                        <div class="panel-body">
                            <ul>
                                <?php
                                foreach($this->CategorieA as $cat){
                                    echo '<li><a href='.$this->url(array(
                                            'controller' => 'public',
                                            'action'     => 'index',
                                            'categoria' => $cat->Nome
                                        ),
                                            'default',true
                                        ).'>' . $cat->Nome . '</a></li>';
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordian" href="#mens">
                                <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                Moto
                            </a>
                        </h4>
                    </div>
                    <div id="mens" class="panel-collapse collapse">
                        <div class="panel-body">
                            <ul>
                                <?php
                                foreach($this->CategorieM as $cat){
                                    echo '<li><a href='.$this->url(array(
                                            'controller' => 'public',
                                            'action'     => 'index',
                                            'categoria' => $cat->Nome
                                        ),
                                            'default',true
                                        ).'>' . $cat->Nome . '</a></li>';
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div><!--/category-products-->

        </div>
    </div>

    <div class="col-sm-9 padding-right">
        <div class="features_items"><!--features_items-->
            <h2 class="title text-center">Chi siamo</h2>
            Chi siamo
        </div><!--features_items-->
    </div>
</div>
    </div>
</section>