<?php $this->headTitle()->append('Chi siamo');?>
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Chi siamo</h2>
                    <img class="border-radius" height="216" width="560" src="<?php echo $this->baseURL();?>/images/home/logo.png" alt="" />
                    <div class="who-div">Un’automobile eccezionale merita un servizio eccezionale.
                        Ci pensano i qualificatissimi tecnici del Vostro Centro BMW Service e una rete perfettamente sintonizzata, grazie a BMW Assistance, di innovative tecnologie di informazione e servizio. Il nostro impegno e la nostra assistenza non garantiscono solo la qualità della Vostra BMW, ma anche il Vostro piacere di guidare.</div>
                </div><!--features_items-->
            </div>
        </div>
    </div>
</section>