<?php $this->headTitle()->append('Chi siamo');?>
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Chi siamo</h2>
                    Chi siamo
                </div><!--features_items-->
            </div>
        </div>
    </div>
</section>