<?php echo $this->doctype() ?>
<html >
<head>
    <?= $this->headMeta(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>

    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="<?php echo $this->baseURL();?>/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->baseURL();?>/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->baseURL();?>/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->baseURL();?>/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="<?php echo $this->baseURL();?>/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
<header id="header"><!--header-->
    <div class="header_top"><!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +39 123 456 7890</a></li>
                            <li><a href="mailto:grp55@tweb.univpm.it"><i class="fa fa-envelope"></i> grp55@tweb.univpm.it</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="http://www.facebook.com"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="http://www.twitter.com"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="http://www.linkedin.com"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="http://plus.google.com"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle"><!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a href=" <?= $this->url(array(
                            'controller' => 'index',
                            'action'     => 'index',
                        ),
                            'default',true
                        );
                        ?>"><img src="<?php echo $this->baseURL();?>/images/home/logo.png" alt="" /></a>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="shop-menu pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-user"></i> Account</a></li>
                            <li><a href="login.html"><i class="fa fa-lock"></i> Login</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <?= $this->render('mainmenu.phtml') ?>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Search"/>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->


<section>
    <div class="container">
        <?php echo $this->layout()->content; ?>
        </div>
    </div>
</section>

<footer id="footer"><!--Footer-->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="companyinfo">
                        <h2><span>e</span>-shopper</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="<?php echo $this->baseURL();?>/images/home/iframe1.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="<?php echo $this->baseURL();?>/images/home/iframe2.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="<?php echo $this->baseURL();?>/images/home/iframe3.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="<?php echo $this->baseURL();?>/images/home/iframe4.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="<?php echo $this->baseURL();?>/images/home/map.png" alt="" />
                        <p>Via Brecce Bianche, Ancona (AN), Italia</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Servizi</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Help-Desk</a></li>
                            <li><a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'index',
                                    'viewStatic' => 'contact'),
                                    'default',true
                                );
                                ?>">Contattaci</a></li>
                            <li><a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'index',
                                    'viewStatic' => 'faq'),
                                    'default',true
                                );
                                ?>">FAQ's</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Link Rapidi</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'index',
                                    'cate' => 'contact'),
                                    'default',true
                                );
                                ?>">Auto</a></li>
                            <li><a href="#">Moto</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Su di noi</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'index',
                                    'viewStatic' => 'who'),
                                    'default',true
                                );
                                ?>">Informazioni sull'azienda</a></li>
                            <li><a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'index',
                                    'viewStatic' => 'copyright'),
                                    'default',true
                                );
                                ?>">Copyright</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
                <p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
            </div>
        </div>
    </div>

</footer><!--/Footer-->
<script src="<?php echo $this->baseURL();?>/js/jquery.js"></script>
<script src="<?php echo $this->baseURL();?>/js/bootstrap.min.js"></script>
<script src="<?php echo $this->baseURL();?>/js/jquery.scrollUp.min.js"></script>
<script src="<?php echo $this->baseURL();?>/js/price-range.js"></script>
<script src="<?php echo $this->baseURL();?>/js/jquery.prettyPhoto.js"></script>
<script src="<?php echo $this->baseURL();?>/js/main.js"></script>
</body>
</html>

