<ul class="nav navbar-nav collapse navbar-collapse">
    <li><a href=" <?= $this->url(array(
            'controller' => 'public',
            'action'     => 'index',
        ),
            'default',true
        );
        ?>" >Home</a></li>
    <li><a href="
                <?= $this->url(array(
            'controller' => 'public',
            'action'     => 'viewstatic',
            'page' => 'who'),
            'default',true
        );
        ?>">Chi Siamo</a></li>
    <li><a href="
                <?= $this->url(array(
            'controller' => 'public',
            'action'     => 'viewstatic',
            'page' => 'where'),
            'default',true
        );
        ?>">Dove Siamo</a></li>
    <li><a href="
                <?= $this->url(array(
            'controller' => 'public',
            'action'     => 'viewstatic',
            'page' => 'contact'),
            'default',true
        );
        ?>">Contatti</a></li>
    <li><a href="
                <?= $this->url(array(
            'controller' => 'public',
            'action'     => 'viewstatic',
            'page' => 'faq'),
            'default',true
        );
        ?>">FAQ</a></li>
</ul>
