
<div class="content-404">
    <img src="<?php echo $this->baseURL();?>/images/404/404.png" class="img-responsive" alt="" />
    <h1><b>OPPS!</b> An error occured</h1>
    <h2><?php echo $this->message ?></h2>
    <p>Uh... So it looks like you brock something. The page you are looking for has up and Vanished.</p>
    <h2><a href=" <?= $this->url(array(
            'controller' => 'index',
            'action'     => 'index',
        ),
            'default',true
        );
        ?>" >Home</a></h2>
    <?php if (isset($this->exception)): ?>

        <h3>Exception information:</h3>
        <p>
            <b>Message:</b> <?php echo $this->exception->getMessage() ?>
        </p>

        <h3>Stack trace:</h3>
        <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

        <h3>Request Parameters:</h3>
        <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

    <?php endif ?>
</div>

