<?php if ($this->pageCount > 1): ?>
    <div id="pagination">
        <?php echo 'Pagina '. $this->current; ?> di <?= $this->pageCount; ?> ---

        <!-- Link alla prima pagina -->
        <?php if (isset($this->previous)): ?>
            <a href="<?= $this->url(array('controller' => 'admin', 'action' => 'modificacancellautente', 'page' => $this->first)); ?>">Inizio</a> |
        <?php else: ?>
            Inizio |
        <?php endif; ?>

        <!-- Link alla pagina precedente -->
        <?php if (isset($this->previous)): ?>
            <a href="<?= $this->url(array('controller' => 'admin', 'action' => 'modificacancellautente', 'page' => $this->previous)); ?>">&lt; Precedente</a> |
        <?php else: ?>
            &lt; Precedente |
        <?php endif; ?>

        <!-- Link alla pagina successiva -->
        <?php if (isset($this->next)): ?>
            <a href="<?= $this->url(array('controller' => 'admin', 'action' => 'modificacancellautente', 'page' => $this->next)); ?>">Successivo &gt;</a> |
        <?php else: ?>
            Successivo &gt; |
        <?php endif; ?>

        <!-- Link all'ultima pagina -->
        <?php if (isset($this->next)): ?>
            <a href="<?= $this->url(array('controller' => 'admin', 'action' => 'modificacancellautente', 'page' => $this->last)); ?>">Fine</a>
        <?php else: ?>
            Fine
        <?php endif; ?>

    </div>
<?php endif; ?>