<?php
echo'<div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Modifica prodotti</h2>
                    <div class="search_box pull-right">
                    <form action="'.$this->url(array('controller' => 'admin','action' => 'redirectorurlcerca',),'default',true).'" method="post">
                            <input name="prodotti[query]" id="query" type="text" placeholder="Cerca prodotto"/>
                        </form>
                    </div>
                    <div  id="cart_items" >
                        <div  class="table-responsive cart_info">
                            <table  class="table table-condensed">
                                <thead>
                                <tr class="cart_menu">
                                    <td class="image">Immagine</td>
                                    <td class="description">Prodotto</td>
                                    <td class="description">Descrizione</td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                </thead>
                                <tbody>';
    foreach($this->Prodotti as $prod){
        $urlfoto = ($prod->Foto=='' || is_null($prod->Foto))?($this->baseURL().'/images/product-details/image-coming-soon.png'):($this->baseURL().'/images/products/'. $prod->Foto);
        echo'<tr>
                                    <td class="cart_product">
                                        <img height="100" width="100" src="'. $urlfoto.'" alt="">
                                    </td>
                                    <td  class="cart_description">
                                        <h4>'.$prod->Nome.'</h4>
                                        <p>ID: '.$prod->id.'</p>
                                    </td>
                                    <td  class="cart_description">
                                        <p>'.$prod->DescrizioneBreve.'</p>
                                    </td>
                                    <td  class="cart_delete">
                                        <p><a class="cart_quantity_delete" href="'.$this->url(array(
				'controller' => 'admin',
				'action'     => 'updateproduct',
				'id' => $prod->id
			),
				'default',true
			).'"><i class="fa fa-pencil">Modifica</i></a></p>
                                        <p><a class="cart_quantity_delete" href="'.$this->url(array(
				'controller' => 'admin',
				'action'     => 'cancellaprodotto',
				'id' => $prod->id
			),
				'default',true
			).'"><i class="fa fa-times">Cancella</i></a></p>
                                    </td>
                                </tr>';
    }
echo'</tbody>
                            </table>
                        </div>
                    </div>';
if($this->Prodotti instanceof Zend_Paginator) {
echo '<div class="text-center">'.$this->paginationControl($this->Prodotti,'Elastic','admin/_paginatorProdotti.phtml').'</div>';
};
echo '</div><!--features_items-->
            </div>';
