<?php
echo'<div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Modifica prodotti</h2>
                    <div  id="cart_items" >
                        <div  class="table-responsive cart_info">
                            <table  class="table table-condensed">
                                <thead>
                                <tr class="cart_menu">
                                    <td class="description">Categoria</td>
                                    <td class="description">Tipo</td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                </thead>
                                <tbody>';
                                foreach($this->Categorie as $cat){
                                    echo'<tr>
                                            <td  class="cart_description">
                                                <h4>'.$cat->Nome.'</h4>
                                                <p>ID: '.$cat->id.'</p>
                                            </td>
                                            <td  class="cart_description">
                                                <p>'.$cat->Tipo.'</p>
                                            </td>
                                            <td  class="cart_delete">
                                                <p><a class="cart_quantity_delete" href="'.$this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'updatecategory',
                                                    'id' => $cat->id
                                                ),
                                                    'default',true
                                                ).'"><i class="fa fa-pencil">Modifica</i></a></p>
                                                <p><a class="cart_quantity_delete" href="'.$this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'cancellacategoria',
                                                    'id' => $cat->id
                                                ),
                                                    'default',true
                                                ).'"><i class="fa fa-times">Cancella</i></a></p>
                                            </td>
                                         </tr>';
                                        }
                            echo'</tbody>
                            </table>
                        </div>
                    </div>';
if($this->Categorie instanceof Zend_Paginator) {
    echo '<div class="text-center">'.$this->paginationControl($this->Categorie,'Elastic','admin/_paginatorCategory.phtml').'</div>';
};
  echo'              </div><!--features_items-->
            </div>';
