<?php
echo '<div class="features_items"><!--features_items-->
    <h2 class="title text-center">MODIFICA Utenti</h2>';
foreach($this->Utenti as $utente){
    echo'<div class="media commnets">
						<div class="media-body">
							<h4 class="media-heading">Nome: </h4>
							<p>'.$utente->Nome .'</p>
							<h4 class="media-heading">Username: </h4>
							<p>'.$utente->Username .'</p>
							<div class="blog-socials">
								<ul>
									<li><a href="'.$this->url(array(
            'controller' => 'admin',
            'action'     => 'updateuser',
            'id' => $utente->idUtenti
        ),
            'default',true
        ).'"><i class="fa fa-pencil"></i>Modifica</a></li>
									<li><a href="'.$this->url(array(
            'controller' => 'admin',
            'action'     => 'cancellauser',
            'id' => $utente->idUtenti
        ),
            'default',true
        ).'"><i class="fa fa-trash-o"></i>Cancella</a></li>
								</ul>
							</div>
						</div>
						</div>';
}
if($this->Utenti instanceof Zend_Paginator) {
    echo '<div class="text-center">'.$this->paginationControl($this->Utenti,'Elastic','admin/_paginatorUtenti.phtml').'</div>';
};