<?php
echo '<div class="features_items"><!--features_items-->
    <h2 class="title text-center">MODIFICA PRODOTTI</h2>';
    foreach($this->Prodotti as $prod){
    echo'<div class="media commnets">
						<a class="pull-left" href="#">
							<img class="media-object" src="'. $this->baseURL().'/images/blog/man-one.jpg" alt="">
						</a>
						<div class="media-body">
							<h4 class="media-heading">'.$prod->Nome.'</h4>
							<p>'.$prod->DescrizioneBreve .'</p>
							<div class="blog-socials">
								<ul>
									<li><a href="'.$this->url(array(
                                                'controller' => 'admin',
                                                'action'     => 'updateproduct',
                                                'id' => $prod->id
                                                 ),
                                                    'default',true
                                                 ).'"><i class="fa fa-pencil"></i>Modifica</a></li>
									<li><a href="'.$this->url(array(
                                                 'controller' => 'admin',
                                                'action'     => 'cancellaprodotto',
                                                'id' => $prod->id
                                                 ),
                                                     'default',true
                                                   ).'"><i class="fa fa-trash-o"></i>Cancella</a></li>
								</ul>
							</div>
						</div>
						</div>';
    }
if($this->Prodotti instanceof Zend_Paginator) {
echo '<div class="text-center">'.$this->paginationControl($this->Prodotti,'Elastic','public/_paginator.phtml').'</div>';
};
